apiVersion: v1
kind: Secret
metadata:
    name: dagster-db-backup-creds
    namespace: lotus-lake
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:rwfHar0=,iv:181vpoGU7I2HZaIbGHXOJx3tGTL7jR/QQI8r3oFXxyg=,tag:Glr0tCXwOuB5IOYQ1o2/yQ==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6JAfdSpT/udjpf/u+4U=,iv:nMVtvfDGHJlDAb0+EWjHTMQfe9XuThDUHdspTMIgBmk=,tag:rj/1HJ7xwmAz7bWy3xDrMw==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcnNmVjhVN0hpK2pvRnVy
            ZGp0QlhZVzNOOHBWekREMHM5V1lKTWFYZ3lRCndoRW1sc3ozakhJelJNU2IySEkv
            VE50YkdmNFF4VElOdXQyeVNoUUp5bkUKLS0tIDdkVUk5SUt0Yzd0Q1h0UFdnYWgy
            cGFRbXFDOGpjUTk0VmlPWVcyT05qb2MK9hMXKEfOQjAoyyLuQVL8xMinxiiTL2wI
            jHohjuXUJTedY9l2gu2n8yScj/SvEor1ftavyDV5i4Q+9am1no69cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T06:18:03Z"
    mac: ENC[AES256_GCM,data:cTrHelbx5xZe41QYaIMQpgF/fif5arcifxCgKo0MwJVHVrxi+DNALRM+m5MfhcTSYLDS/dYcJb4CetFkEguAIRO4lYdgP1Vw8hxd6cTkgZy6dGIrM9d1nO71x0mi4F8xKM30Pd+3STsRfX/35GG6twkhAP4B5h/iOja5m9s3ryg=,iv:YCJtmtbG9bX97JT4GL00052s+EMSpFqdcuXDLx38qzI=,tag:DyCpk51zLHwaIp1oTuedRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
