# ==============================================================================
# Dagster DB Backup Credentials (SeaweedFS S3)
# ==============================================================================
# SOPS encrypted - edit with: sops deploy/dagster/backup-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: dagster-db-backup-creds
    namespace: lotus-lake
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:u6aa8oI=,iv:hkvLliwhTLFXaxBjKGdEh980D0DC7f3BHQsw/Z51UYM=,tag:7Cvmvk45L16B6bXYHGvNew==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4eReEUM=,iv:L2Qm5NW0p4xn2MM6iLeGhCEjmtSMpyxSsRzFhAnVNsQ=,tag:G9ZjR3v+uRf5akdtEkfcwg==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQTVnWUkxdjFVTTVuK1c4
            R2ZpeERXa0xvTHFNY0VSdExpU3lNaTEzdDEwCitUbXhNc3Mrd24xbkRkWUFrbTR3
            Snh5N0FiUnRIMmhyUGtpS0dzZk5kOUkKLS0tIDZ3VVlsOHZUODBmcExMYzcvcVll
            VVlaNlJJL0tRVWJKeTg3TU1NdkdVbTQKO/YK0ysHxQ2ELh1uCP5wjux7+U17pkD1
            BWgFHpS6qeX8BSqouSik+kAcydsWB9vW9ycg7u1JcLKDSDKwrdDwhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T07:17:29Z"
    mac: ENC[AES256_GCM,data:+YjqVez27bZO2txHBwC70LppvXLSIUVamoIGnxcSBvIZURP7ih6qxzHHZUmXGsKeWKij91P6LY9Y08vCBpNtB9hdBJDg6l1Q7tqT932uGhZSVl8Abc2hstx3xYOSa+k0K/FLRJGxN8ndk2jA14ilrqEXpAisqJFmktV3D34zEVI=,iv:kTc/weD+aPUccKo1NJy/npo/BsrBDR+VlNsIsHJCbOE=,tag:OLs8JFESeZTpQIgEdeQzxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
