# ==============================================================================
# Dagster Kustomization (lotus-lake)
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - database.yaml
  - backup-secret.yaml
  - release.yaml
