# ==============================================================================
# lotus-lake Deployment
# ==============================================================================
# Deploy to h-kube cluster via Flux
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dagster
