server:
  workers: 1
  
coordinator:
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"

additionalCatalogs:
  iceberg: |
    connector.name=iceberg
    iceberg.catalog.type=nessie
    iceberg.nessie-catalog.uri=http://nessie.nessie.svc.cluster.local:19120/api/v2
    iceberg.nessie-catalog.default-warehouse-dir=s3://landing/iceberg/
    iceberg.nessie-catalog.ref=main
    fs.native-s3.enabled=true
    s3.endpoint=http://minio.minio.svc.cluster.local:9000
    s3.path-style-access=true
    s3.region=us-east-1
    s3.aws-access-key=${ENV:MINIO_ACCESS_KEY}
    s3.aws-secret-key=${ENV:MINIO_SECRET_KEY}

server:
  env:
    - name: MINIO_ACCESS_KEY
      value: "minio"
    - name: MINIO_SECRET_KEY
      value: "minio123"