# ==============================================================================
# Trino Namespace
# ==============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: lotus-lake
