# ==============================================================================
# lotus-lake S3 Credentials
# ==============================================================================
# SOPS encrypted - edit with: sops deploy/trino/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: lotus-lake-s3-creds
    namespace: lotus-lake
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:dNJq/BA=,iv:y5MxWnLAQ84pVVqaFxr0CqJK1SRMn+9Llg00zEE83S8=,tag:L8Ks85SN+WtRdGGtHW5YKA==,type:str]
    secret-key: ENC[AES256_GCM,data:PozCzig=,iv:vN4+BYVUWha/jXzlX95IQXMrZnb4+S+3D+t6ZVJnSLQ=,tag:bFiPANljmZvgO9esJ/NfRQ==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbTVBS1I0UFBRL2FuVHN5
            N3hka0FOeHNudTBjVmZOcnpROENZdllma2dJCmJpSy93TE04QWF5bTFhNHQwQi9J
            L2d0YXpPUURocWZISVNLTTBGV0tnMjQKLS0tIFdLb3RkOHJyZ3JXZm1oSHY3SlhF
            Vzd0L0dRUmcxMXFyTDI3ZGUwR0FlbTgKNCURcwBipEuyfto5IVN6ut+Kbn2GS0mC
            /O0k9PACLYCUjaU2SdlALpok22h70TBnolXAf49Tg+8GGMfAJSKZUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T07:09:27Z"
    mac: ENC[AES256_GCM,data:e2bQQVe79TJnKPms1aNkRvK2Wlu4idR31A4US4D6ZqxdFFS3emqRGN4aY/8Ec9SjmiC/fjDTTjv1AZBkc7lwFUmOff8yrUW0YnW4Z4iiVtG0rcUVUPOMnOVDyaPzAfgMgZhcf5UF2aht+z+iGlYzpfStQAcTPld9MzhNF2V9gcE=,iv:DER/uWDwILDwpyn4vXWFRa7R9pgEEmQDKVPya3hT/Pk=,tag:rlmtFmWI+w85IbtSvu1dRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
